# Generated by Django 4.2 on 2024-02-18 17:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehabilitationcategory',
            options={'verbose_name': 'Категорий реабилитации', 'verbose_name_plural': 'Категории реабилитации'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='Patient_instructions',
            field=models.TextField(verbose_name='Инструкции для пациента'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='Patient_instructions_en',
            field=models.TextField(null=True, verbose_name='Инструкции для пациента'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='Patient_instructions_ru',
            field=models.TextField(null=True, verbose_name='Инструкции для пациента'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='Patient_instructions_tr',
            field=models.TextField(null=True, verbose_name='Инструкции для пациента'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_description',
            field=models.TextField(verbose_name='Описание анализа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_description_en',
            field=models.TextField(null=True, verbose_name='Описание анализа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_description_ru',
            field=models.TextField(null=True, verbose_name='Описание анализа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_description_tr',
            field=models.TextField(null=True, verbose_name='Описание анализа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_name',
            field=models.CharField(max_length=255, verbose_name='Название анализа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название анализа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название анализа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Название анализа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='expected_results',
            field=models.TextField(verbose_name='Ожидаемые результаты'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='expected_results_en',
            field=models.TextField(null=True, verbose_name='Ожидаемые результаты'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='expected_results_ru',
            field=models.TextField(null=True, verbose_name='Ожидаемые результаты'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='expected_results_tr',
            field=models.TextField(null=True, verbose_name='Ожидаемые результаты'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='procedure_description',
            field=models.TextField(verbose_name='Описание процедуры'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='procedure_description_en',
            field=models.TextField(null=True, verbose_name='Описание процедуры'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='procedure_description_ru',
            field=models.TextField(null=True, verbose_name='Описание процедуры'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='procedure_description_tr',
            field=models.TextField(null=True, verbose_name='Описание процедуры'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='promotion',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servises.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='results_delivery_time',
            field=models.CharField(max_length=255, verbose_name='Время доставки результатов'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='results_delivery_time_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Время доставки результатов'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='results_delivery_time_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Время доставки результатов'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='results_delivery_time_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Время доставки результатов'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='analysissubcategory',
            name='analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servises.analysis', verbose_name='Анализы'),
        ),
        migrations.AlterField(
            model_name='analysissubcategory',
            name='subcategory_description',
            field=models.TextField(verbose_name='Описание подкатегории'),
        ),
        migrations.AlterField(
            model_name='analysissubcategory',
            name='subcategory_description_en',
            field=models.TextField(null=True, verbose_name='Описание подкатегории'),
        ),
        migrations.AlterField(
            model_name='analysissubcategory',
            name='subcategory_description_ru',
            field=models.TextField(null=True, verbose_name='Описание подкатегории'),
        ),
        migrations.AlterField(
            model_name='analysissubcategory',
            name='subcategory_description_tr',
            field=models.TextField(null=True, verbose_name='Описание подкатегории'),
        ),
        migrations.AlterField(
            model_name='analysissubcategory',
            name='subcategory_name',
            field=models.CharField(max_length=255, verbose_name='Подкатегория анализа'),
        ),
        migrations.AlterField(
            model_name='analysissubcategory',
            name='subcategory_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подкатегория анализа'),
        ),
        migrations.AlterField(
            model_name='analysissubcategory',
            name='subcategory_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подкатегория анализа'),
        ),
        migrations.AlterField(
            model_name='analysissubcategory',
            name='subcategory_name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Подкатегория анализа'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='diagnostic_name',
            field=models.CharField(max_length=100, verbose_name='Название диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='diagnostic_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='diagnostic_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='diagnostic_name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='diagnostic_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servises.diagnosticsubcategory', verbose_name='Подкатегория диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='image',
            field=models.ImageField(upload_to='image_diagnostic/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='promotion',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
        migrations.AlterField(
            model_name='diagnosticcategory',
            name='diagnostic_category_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название категории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticcategory',
            name='diagnostic_category_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticcategory',
            name='diagnostic_category_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticcategory',
            name='diagnostic_category_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticcategory',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servises.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='diagnostic_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servises.diagnosticcategory', verbose_name='Категория диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='diagnostic_subcategory_description',
            field=models.TextField(verbose_name='Описание подкатегории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='diagnostic_subcategory_description_en',
            field=models.TextField(null=True, verbose_name='Описание подкатегории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='diagnostic_subcategory_description_ru',
            field=models.TextField(null=True, verbose_name='Описание подкатегории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='diagnostic_subcategory_description_tr',
            field=models.TextField(null=True, verbose_name='Описание подкатегории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='diagnostic_subcategory_name',
            field=models.CharField(max_length=100, verbose_name='Название подкатегории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='diagnostic_subcategory_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название подкатегории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='diagnostic_subcategory_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название подкатегории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='diagnostic_subcategory_name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название подкатегории диагностики'),
        ),
        migrations.AlterField(
            model_name='diagnosticsubcategory',
            name='image',
            field=models.ImageField(upload_to='image_diagnostic/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='about_procedure',
            field=ckeditor.fields.RichTextField(verbose_name='Описание процедур'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='about_procedure_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание процедур'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='about_procedure_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание процедур'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='about_procedure_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание процедур'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='about_service',
            field=ckeditor.fields.RichTextField(verbose_name='Описание услуг'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='about_service_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание услуг'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='about_service_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание услуг'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='about_service_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание услуг'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='polyclinic_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servises.polycliniccategory', verbose_name='Категория поликлиники'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='polyclinic_name',
            field=models.CharField(max_length=100, verbose_name='Название поликлиники'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='polyclinic_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название поликлиники'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='polyclinic_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название поликлиники'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='polyclinic_name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название поликлиники'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='price_first_meet',
            field=models.IntegerField(verbose_name='Цена первичной встречи'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='price_second_meet',
            field=models.IntegerField(verbose_name='Цена повторной встречи'),
        ),
        migrations.AlterField(
            model_name='polycliniccategory',
            name='polyclinic_category_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название категории поликлиники'),
        ),
        migrations.AlterField(
            model_name='polycliniccategory',
            name='polyclinic_category_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории поликлиники'),
        ),
        migrations.AlterField(
            model_name='polycliniccategory',
            name='polyclinic_category_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории поликлиники'),
        ),
        migrations.AlterField(
            model_name='polycliniccategory',
            name='polyclinic_category_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории поликлиники'),
        ),
        migrations.AlterField(
            model_name='polycliniccategory',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servises.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название региона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='название региона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='название региона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='название региона'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='image',
            field=models.ImageField(upload_to='image_rehabilitation/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='rehabilitation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rehab_cat', to='servises.rehabilitationcategory', verbose_name='Категории реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='rehabilitation_description',
            field=models.TextField(verbose_name='Описание реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='rehabilitation_description_en',
            field=models.TextField(null=True, verbose_name='Описание реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='rehabilitation_description_ru',
            field=models.TextField(null=True, verbose_name='Описание реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='rehabilitation_description_tr',
            field=models.TextField(null=True, verbose_name='Описание реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='rehabilitation_name',
            field=models.CharField(max_length=100, verbose_name='Название реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='rehabilitation_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='rehabilitation_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='rehabilitation_name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitationcategory',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servises.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='rehabilitationcategory',
            name='rehabilitation_category_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категорий реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitationcategory',
            name='rehabilitation_category_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категорий реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitationcategory',
            name='rehabilitation_category_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категорий реабилитации'),
        ),
        migrations.AlterField(
            model_name='rehabilitationcategory',
            name='rehabilitation_category_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категорий реабилитации'),
        ),
    ]
