# Generated by Django 4.2 on 2024-02-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0004_analysiscategory_remove_analysis_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresscenter',
            name='region',
        ),
    ]
