# Generated by Django 4.2 on 2024-02-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='middle_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='middle_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='middle_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization_en',
            field=models.TextField(blank=True, default='Доктор практикант', null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization_ru',
            field=models.TextField(blank=True, default='Доктор практикант', null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization_tr',
            field=models.TextField(blank=True, default='Доктор практикант', null=True, verbose_name='Специализация'),
        ),
    ]
