# Generated by Django 4.2 on 2024-02-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_doctor_options_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='first_name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='middle_name_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization_ky',
            field=models.TextField(default='Доктор практикант', null=True, verbose_name='Специализация'),
        ),
    ]
