# Generated by Django 4.2 on 2024-02-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_doctor_first_name_ky_doctor_last_name_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
