# Generated by Django 4.2 on 2024-02-16 05:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='answer_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответы'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='answer_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответы'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='answer_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответы'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='question_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вопросы'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='question_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вопросы'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='question_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вопросы'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
