# Generated by Django 4.2 on 2024-02-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_body_en_remove_article_body_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Название блога'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название FAQ'),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название FAQ'),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название FAQ'),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Название FAQ'),
        ),
    ]
