# Generated by Django 4.2 on 2024-02-25 11:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название блога'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='answer_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответы'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='question_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вопросы'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название FAQ'),
        ),
    ]
