# Generated by Django 4.2 on 2024-02-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_description_ky_article_title_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='qa_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
