# Generated by Django 4.2 on 2024-02-25 11:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutcompany_created_aboutcompany_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ourcommand',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ourcommand',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ourcommandprofession',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ourcommandprofession',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ourexperience',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ourexperience',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Обязанности'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
