# Generated by Django 4.2 on 2024-02-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutcompany_description_ky_aboutcompany_title_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='about_company_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='ourcommand',
            name='our_command_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='ourcommandprofession',
            name='our_command_profession_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='ourexperience',
            name='our_experience_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
